# params.yaml
data:
  raw_dir: "data/raw"
  processed_dir: "data/processed"
  test_size: 0.2
  target: "Survived"  # Added from your error logs
  features:
    numerical: ["Age", "Fare"]
    categorical: ["Sex", "Embarked"]

preprocessing:
 numeric_strategy : "median"
 categorical_strategy : "most_frequent"
model:
  type: "random_forest"
  params:
    n_estimators: 100
    max_depth: 5
    random_state: 42

paths:
  metrics_file: "reports/metrics.json"
  model_output: "models/model.joblib"
  model_dir : "models/"

mlflow:
  tracking_uri: https://dagshub.com/yahiakhalaf14/MLOps-labs.mlflow
  experiment_name: Titanic-Experiment
